<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Apigoogle\autoload'             => __DIR__ . '/autoload.php',
  'Apigoogle\Client'                       => __DIR__ . '/Client.php',
  'Apigoogle\Collection'                       => __DIR__ . '/Collection.php',
  'Apigoogle\Config'                       => __DIR__ . '/Config.php',
  'Apigoogle\Exception'                       => __DIR__ . '/Exception.php',
  'Apigoogle\Model'                       => __DIR__ . '/Model.php',
  'Apigoogle\Module'                       => __DIR__ . '/Module.php',
  'Apigoogle\Service'                       => __DIR__ . '/Service.php',
  'Apigoogle\Utils'                       => __DIR__ . '/Utils.php',
  'Apigoogle\Google'                       => __DIR__ . '/Google.php',
  'Apigoogle\base'                       => __DIR__ . '/base.php',



  'Apigoogle\AccessToken\Revoke'              => __DIR__ . '/AccessToken/Revoke.php',
  'Apigoogle\AccessToken\Verify'           => __DIR__ . '/AccessToken/Verify.php',

  'Apigoogle\AuthHandler\AuthHandlerFactory'           => __DIR__ . '/AuthHandler/AuthHandlerFactory.php',
  'Apigoogle\AuthHandler\Guzzle5AuthHandler'           => __DIR__ . '/AuthHandler/Guzzle5AuthHandler.php',
  'Apigoogle\AuthHandler\Guzzle6AuthHandler'           => __DIR__ . '/AuthHandler/Guzzle6AuthHandler.php',



  'Apigoogle\Cache\Apc'   => __DIR__ . '/Cache/Apc.php',
  'Apigoogle\Cache\Exception'   => __DIR__ . '/Cache/Exception.php',
  'Apigoogle\Cache\File'   => __DIR__ . '/Cache/File.php',
  'Apigoogle\Cache\Memcache'   => __DIR__ . '/Cache/Memcache.php',
  'Apigoogle\Cache\Null'   => __DIR__ . '/Cache/Null.php',



  'Apigoogle\Http\Batch'   => __DIR__ . '/Http/Batch.php',
  'Apigoogle\Http\MediaFileUpload'   => __DIR__ . '/Http/MediaFileUpload.php',
  'Apigoogle\Http\REST'   => __DIR__ . '/Http/REST.php',


  'Apigoogle\Service\Drive'   => __DIR__ . '/Service/Drive.php',
  'Apigoogle\Service\YouTube'   => __DIR__ . '/Service/YouTube.php',


   'Apigoogle\Task\Exception'   => __DIR__ . '/Task/Exception.php',
   'Apigoogle\Task\Retryable'   => __DIR__ . '/Task/Retryable.php',
   'Apigoogle\Task\Runner'   => __DIR__ . '/Task/Runner.php',

   'Apigoogle\Utils\URITemplate'   => __DIR__ . '/Utils/URITemplate.php',


);
